-- MySQL Script generated by MySQL Workbench
-- Thu Apr 12 20:14:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Notification` (
  `idNotification` INT NOT NULL AUTO_INCREMENT,
  `idUsuarioOrigen` INT NOT NULL,
  `idUsuarioDestino` INT NOT NULL,
  `fechahora` DATETIME NULL,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`idNotification`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrdenServicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrdenServicio` (
  `idOrdenServicio` INT NOT NULL AUTO_INCREMENT,
  `idCliente` VARCHAR(45) NOT NULL,
  `fechahora` DATETIME NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `cantidadProductos` INT NOT NULL,
  `costoTotal` FLOAT NOT NULL,
  PRIMARY KEY (`idOrdenServicio`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
